"""changed type of default_clothing from BookCharacterTemplate

Revision ID: 3bfa0e26b476
Revises: 462ead3a1dd3
Create Date: 2026-03-19 13:31:10.306504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bfa0e26b476'
down_revision = '462ead3a1dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.alter_column('default_clothing',
               existing_type=sa.VARCHAR(length=200),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.alter_column('default_clothing',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
