"""added relationship and id of Personalization to ReadingProgress

Revision ID: 462ead3a1dd3
Revises: b18aab3e920f
Create Date: 2026-03-12 16:24:55.269684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ead3a1dd3'
down_revision = 'b18aab3e920f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personalization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personalizations', ['personalization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personalization_id')

    # ### end Alembic commands ###
