"""deleted uniqueness from role from BookCharacterTemplate

Revision ID: b18aab3e920f
Revises: ea179c27727b
Create Date: 2026-02-26 12:19:06.815244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18aab3e920f'
down_revision = 'ea179c27727b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('book_character_templates_role_key'), type_='unique')
        batch_op.create_unique_constraint('uq_book_role', ['book_id', 'role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_book_role', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('book_character_templates_role_key'), ['role'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
