"""added Personalization, BookCharacterTemplate, PersonalizationCharacters, ReadingProgress

Revision ID: e19a6061b68e
Revises: 
Create Date: 2026-02-24 14:14:27.343992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19a6061b68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customizable', sa.Boolean(), nullable=False))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('personalization_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customizable', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'book_character_templates', ['template_id'], ['id'])

    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_page_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pages', ['current_page_id'], ['id'])
        batch_op.drop_column('current_page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_page', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_page_id')

    with op.batch_alter_table('personalization_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customizable')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('is_cover',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.drop_column('customizable')

    # ### end Alembic commands ###
