"""added uniqueness to role in BookCharacterTemplate

Revision ID: ea179c27727b
Revises: e19a6061b68e
Create Date: 2026-02-26 00:03:51.854188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea179c27727b'
down_revision = 'e19a6061b68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['role'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_character_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
